version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ci-blog-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: ci-blog-app-nginx
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
